version: '3'

services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data